### PR TITLE
Add `symbol` type Workaround

### LINKED ISSUE #34: TS2411:  Property '[Symbol.unscopables]' of type is not assignable
* **Node Version:**: 16.13.2
* **comment-json Version**: 4.2.2 

When upgrading to package 4.2.2 from 4.1.1 
I'm getting the following errors during compile time:
I tried commenting out any references to the module but it keeps appearing.

```cmd
node_modules/typescript/lib/lib.es2015.iterable.d.ts:60:5 - error TS2411: Property '[Symbol.iterator]' of type '() => IterableIterator<TValue>' is not assignable to 'symbol' index type 'CommentToken'.
       [Symbol.iterator](): IterableIterator<T>;

node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts:99:5 - error TS2411: Property '[Symbol.unscopables]' of type '() => { copyWithin: boolean; entries: boolean; fill: boolean; find: boolean; findIndex: boolean; keys: boolean; values: boolean; }' is not assignable to 'symbol' index type 'CommentToken'.
       [Symbol.unscopables](): {
       copyWithin: boolean;
...
       values: boolean;
       };
```

### PR DESCRIPTION
**Pull request by manuth**
Currently, this module doesn't work when using with `typescript` and its `--build` or `-b` command line argument.
This error has been described in #34.

Changes made in this PR will patch the type declarations in a way to prevent said errors while still maintaining the ability to query comments using the newly introduced `CommentSymbol` type.

Merging this PR will fix #34 

> Remark:
> This workaround will be obsolete once the related PR on TypeScript's side has been merged:
> https://github.com/microsoft/TypeScript/pull/49746

### CODE REVIEW

**Comment by kaelzhang** [comment]
Landed in `4.2.3`
