### ISSUE TITLE
TS2411:  Property '[Symbol.unscopables]' of type is not assignable

### ISSUE THREAD

**Issue by DaanV2** [kaelzhang/node-comment-json#34]
* **Node Version:**: 16.13.2
* **comment-json Version**: 4.2.2 

When upgrading to package 4.2.2 from 4.1.1 
I'm getting the following errors during compile time:
I tried commenting out any references to the module but it keeps appearing.

```cmd
node_modules/typescript/lib/lib.es2015.iterable.d.ts:60:5 - error TS2411: Property '[Symbol.iterator]' of type '() => IterableIterator<TValue>' is not assignable to 'symbol' index type 'CommentToken'.
       [Symbol.iterator](): IterableIterator<T>;

node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts:99:5 - error TS2411: Property '[Symbol.unscopables]' of type '() => { copyWithin: boolean; entries: boolean; fill: boolean; find: boolean; findIndex: boolean; keys: boolean; values: boolean; }' is not assignable to 'symbol' index type 'CommentToken'.
       [Symbol.unscopables](): {
       copyWithin: boolean;
...
       values: boolean;
       };
```
